import { buildMissingField } from "../utils/fieldBuilder.js";

export default function mergeOutputs({
  meta,
  napData,
  urlData,
  linkRegistry,
  brandData,
  catalogData,
  deptData,
  financeData,
  geoData,
  historyData,
  positioningData,
  inventoryData,
  serviceData,
  partsData,
  buyerData,
  seasonalityData,
  communityData,
  claimsData,
  themesData,
  platformData,
  operationalData,
  competitiveData,
}) {
  return {
    meta: {
      crawledUrl: meta?.crawledUrl || null,
      crawlDate: meta?.crawlDate || new Date().toISOString(),
      crawlDurationMs: meta?.crawlDurationMs || 0,
      totalPagesVisited: meta?.totalPagesVisited || 0,
      pagesFetchedOk: meta?.pagesFetchedOk || 0,
      pagesFetchFailed: meta?.pagesFetchFailed || 0,
      linksDiscovered: meta?.linksDiscovered || 0,
      robotsTxt: meta?.robotsTxt || null,
      platform: platformData?.platform || null,
      completenessScore: 0,
      confidenceSummary: null,
      crawlLog: [],
    },
    sections: {
      s2_nap: napData || {},
      s3_business_history: historyData || {},
      s4_positioning: positioningData || {},
      s5_brands: brandData || [],
      s5b_catalog: catalogData || {},
      s6_inventory: inventoryData || {},
      s7_departments: deptData || {},
      s8_finance: financeData || {},
      s9_service: serviceData || {},
      s10_parts: partsData || {},
      s11_geo: geoData || {},
      s12_buyer_psychology: buyerData || { profiles: [], additionalBuyerGroups: buildMissingField("No buyer psychology data extracted") },
      s13_seasonality: seasonalityData || {},
      s14_community: communityData || {},
      s15_competitive: competitiveData || {},
      s16_claims: claimsData || {},
      s17_themes: themesData || {},
      s18_operational_rules: operationalData || {},
      s19_deploymentUrls: urlData || {},
      s19_linkRegistry: linkRegistry || [],
      s20_crawlAudit: { gaps: [], critical: [], summary: {} },
    },
  };
}
