function leafVal(node) {
  if (!node) return "—";
  if (typeof node === "object" && "value" in node) {
    const v = node.value;
    if (v === null || v === undefined) return "—";
    if (Array.isArray(v)) {
      if (v.length && v[0]?.url) {
        return v.map((i) => `${i.brand || "Brand"}: ${i.url}`).join("; ");
      }
      return v.map((i) => typeof i === "object" ? JSON.stringify(i) : i).join("; ");
    }
    return String(v);
  }
  return String(node);
}

function section(title, entries) {
  let out = `\n## ${title}\n`;
  for (const [label, node] of entries) {
    const conf = node?.confidence || "—";
    const reason = node?.reason ? ` — *${node.reason}*` : "";
    out += `- **${label}** [${conf}]: ${leafVal(node)}${reason}\n`;
  }
  return out;
}

/**
 * Generates a markdown intelligence packet matching the client report format.
 */
export default function exportPacket(masterJson) {
  const s = masterJson.sections;
  const meta = masterJson.meta;
  const summary = meta.confidenceSummary || {};

  let md = `# MASTER INTELLIGENCE PACKET\n`;
  md += `Generated by LinkScout Intelligence Crawler\n\n`;
  md += `## DATA COVERAGE\n`;
  md += `- Crawled URL: ${meta.crawledUrl}\n`;
  md += `- Pages visited: ${meta.totalPagesVisited}\n`;
  md += `- Links discovered: ${meta.linksDiscovered}\n`;
  md += `- Completeness: ${meta.completenessScore}%\n`;
  md += `- VERIFIED: ${summary.verifiedCount} | INFERRED: ${summary.inferredCount} | MISSING: ${summary.missingCount}\n`;
  md += `- Platform: ${leafVal(meta.platform)}\n`;
  md += `- Crawl duration: ${meta.crawlDurationMs}ms\n\n`;

  md += section("2. VERIFIED ENTITY / NAP", [
    ["Dealership Name", s.s2_nap.dealershipName],
    ["Legal Name", s.s2_nap.legalName],
    ["Address", { value: [s.s2_nap.address?.street, s.s2_nap.address?.city, s.s2_nap.address?.state, s.s2_nap.address?.zip].map(leafVal).filter((x) => x !== "—").join(", "), confidence: s.s2_nap.address?.city?.confidence }],
    ["Phone", s.s2_nap.phone],
    ["Sales Hours", s.s2_nap.salesHours],
    ["Service Hours", s.s2_nap.serviceHours],
    ["Google Business URL", s.s2_nap.googleBusinessUrl],
    ["Logo URL", s.s2_nap.logoUrl],
  ]);

  md += section("4. CORE BUSINESS POSITIONING", [
    ["Primary Type", s.s4_positioning?.primaryType],
    ["Franchise Structure", s.s4_positioning?.franchiseStructure],
    ["Category", s.s4_positioning?.category],
    ["Differentiators", s.s4_positioning?.differentiators],
  ]);

  md += `\n## 5. BRAND HIERARCHY\n`;
  for (const brand of s.s5_brands || []) {
    md += `- **${leafVal(brand.brandName)}** — Parent: ${leafVal(brand.parentCompany)} | Lines: ${leafVal(brand.productLines)} | Role: ${leafVal(brand.authorityRole)}\n`;
  }

  md += section("6. INVENTORY STRATEGY", [
    ["New/Used Mix", s.s6_inventory?.newUsedMix],
    ["Brand Priority", s.s6_inventory?.brandPriority],
    ["Trade-in Policy", s.s6_inventory?.tradeInPolicy],
    ["Buy-Outright", s.s6_inventory?.buyOutrightPolicy],
  ]);

  md += section("8. FINANCE", [
    ["Financing Offered", s.s8_finance?.financingOffered],
    ["Lenders", s.s8_finance?.lenders],
    ["Credit Programs", s.s8_finance?.creditPrograms],
    ["Compliance Language", s.s8_finance?.complianceSafeLanguage],
  ]);

  md += section("9. SERVICE", [
    ["Brands Serviced", s.s9_service?.brandsServiced],
    ["Specialties", s.s9_service?.specialties],
    ["Accessory Install", s.s9_service?.accessoryInstall],
  ]);

  md += section("11. GEO MARKET", [
    ["Primary City", s.s11_geo?.primaryCity],
    ["County", s.s11_geo?.county],
    ["Metro Market", s.s11_geo?.metroMarket],
    ["Nearby Cities", s.s11_geo?.nearbyCities],
  ]);

  md += `\n## 19. DEPLOYMENT URLS\n`;
  for (const [key, node] of Object.entries(s.s19_deploymentUrls || {})) {
    const reason = node?.reason ? ` — *${node.reason}*` : "";
    md += `- **${key}** [${node?.confidence}]: ${leafVal(node)}${reason}\n`;
  }

  md += `\n## 20. CRAWL AUDIT — GAPS WITH REASONS\n`;
  const audit = s.s20_crawlAudit || s.s20_missingItems || {};
  if (audit.critical?.length) {
    md += `\n### Critical Gaps\n`;
    for (const item of audit.critical) md += `- **${item.field}**: ${item.reason || item.notes}\n`;
  }
  if (audit.gaps?.length) {
    md += `\n### All Missing Fields (${audit.gaps.length})\n`;
    for (const item of audit.gaps.slice(0, 50)) {
      md += `- ${item.field}: ${item.reason}\n`;
    }
    if (audit.gaps.length > 50) md += `- ...and ${audit.gaps.length - 50} more\n`;
  }

  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "intelligence_packet.md";
  a.click();
  URL.revokeObjectURL(url);
}
